name: Build

on:
  push:
    branches: [ master ]
  pull_request:
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm:latest
    name: Build package
    steps:
      - uses: actions/checkout@v4
      - name: Make application
        run: |
          chmod +x generate_release.sh
          ./generate_release.sh
      - name: Publish build to GH Actions
        uses: actions/upload-artifact@v4
        with:
          path: 2DSaver.zip
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            2DSaver.zip
